import type { LauncherCatalog } from "@vcg/launcher-catalog";

// Generated by `pnpm prepare:catalog`; edit catalog manifests or launcher-policy.json.
export const launcherCatalog = {
  "schemaVersion": 1,
  "museum": {
    "id": "vibecoded-museum",
    "title": "VibeCoded Museum",
    "entrypoint": "https://vibecoded.games",
    "context": "VIBECODED.GAMES / ONLINE",
    "searchTerms": [
      "museum",
      "collection",
      "web",
      "games"
    ]
  },
  "launchBudgets": {
    "local": {
      "slowAfterMs": 5000,
      "heartbeatTimeoutMs": 8000,
      "timeoutMs": 15000
    },
    "remote": {
      "slowAfterMs": 10000,
      "heartbeatTimeoutMs": 15000,
      "timeoutMs": 30000
    }
  },
  "entries": [
    {
      "id": "vibebots",
      "version": "hosted-5b5d17ef-2026-07-19",
      "title": "VibeBots",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://vibebots.randroid.dev/mine",
      "network": "required",
      "compatibilityStatus": "partial",
      "surface": "museum",
      "displayIndex": "M1",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "robots"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Partial"
    },
    {
      "id": "mi-casa-es-su-casa",
      "version": "hosted-0c868be6-2026-07-19",
      "title": "Mi Casa Es Su Casa",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://mi-casa-es-su-casa.vercel.app",
      "network": "required",
      "compatibilityStatus": "unverified",
      "surface": "museum",
      "displayIndex": "M2",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "casa"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "determined",
      "version": "hosted-7d9a38dc-2026-07-19",
      "title": "Determined",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://determined-khaki.vercel.app",
      "network": "required",
      "compatibilityStatus": "partial",
      "surface": "museum",
      "displayIndex": "M3",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "word",
        "game"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Partial"
    },
    {
      "id": "circuit-shift",
      "version": "1.0.0",
      "title": "Circuit Shift",
      "publisher": "VCG Console",
      "runtime": "local-web",
      "entrypoint": "builtin:circuit-shift",
      "network": "offline",
      "compatibilityStatus": "partial",
      "surface": "retro",
      "displayIndex": "R1",
      "searchDetail": "Built-in retro game",
      "searchTerms": [
        "circuit",
        "shift",
        "puzzle",
        "tiles",
        "offline",
        "built",
        "in"
      ],
      "summary": "Original offline puzzle · controller ready",
      "statusLabel": "Built in"
    },
    {
      "id": "nes-super-mario-bros-duck-hunt",
      "version": "operator-content-23ec3f6b-2026-08-19",
      "title": "Super Mario Bros. + Duck Hunt",
      "publisher": "Nintendo",
      "runtime": "libretro",
      "entrypoint": "libretro:mesen",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "R2",
      "searchDetail": "NES game",
      "searchTerms": [
        "super mario bros",
        "duck hunt",
        "mario",
        "nes",
        "nintendo",
        "mesen"
      ],
      "summary": "Needs your own NES ROM · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "nes-metal-gear",
      "version": "operator-content-1abb14a6-2026-08-19",
      "title": "Metal Gear",
      "publisher": "Konami",
      "runtime": "libretro",
      "entrypoint": "libretro:mesen",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "R3",
      "searchDetail": "NES game",
      "searchTerms": [
        "metal gear",
        "nes",
        "nintendo",
        "konami",
        "mesen"
      ],
      "summary": "Needs your own NES ROM · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "snes-yoshis-island",
      "version": "operator-content-bd763c1a-2026-08-19",
      "title": "Yoshi's Island",
      "publisher": "Nintendo",
      "runtime": "libretro",
      "entrypoint": "libretro:snes9x",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "R4",
      "searchDetail": "SNES game",
      "searchTerms": [
        "yoshis island",
        "yoshi",
        "super mario world 2",
        "snes",
        "nintendo",
        "snes9x"
      ],
      "summary": "Needs your own SNES ROM · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "snes-donkey-kong-country-2",
      "version": "operator-content-b79c2bb8-2026-08-19",
      "title": "Donkey Kong Country 2",
      "publisher": "Nintendo",
      "runtime": "libretro",
      "entrypoint": "libretro:snes9x",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "R5",
      "searchDetail": "SNES game",
      "searchTerms": [
        "donkey kong country 2",
        "donkey kong",
        "diddy kong",
        "snes",
        "nintendo",
        "snes9x"
      ],
      "summary": "Needs your own SNES ROM · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "retro-2048",
      "version": "qualification-candidate-2026-07-23",
      "title": "2048",
      "publisher": "Gabriele Cirulli / Libretro",
      "runtime": "libretro",
      "entrypoint": "libretro:2048",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "Q1",
      "searchDetail": "Retro qualification candidate",
      "searchTerms": [
        "libretro",
        "smoke",
        "test",
        "public",
        "domain",
        "offline"
      ],
      "summary": "Contentless public-domain core · artifact qualification pending",
      "statusLabel": "Candidate"
    }
  ]
} as const satisfies LauncherCatalog;
