import type { LauncherCatalog } from "@vcg/launcher-catalog";

// Generated by `pnpm prepare:catalog`; edit catalog manifests or launcher-policy.json.
export const launcherCatalog = {
  "schemaVersion": 1,
  "museum": {
    "id": "vibecoded-museum",
    "title": "VibeCoded Museum",
    "entrypoint": "https://vibecoded.games",
    "context": "VIBECODED.GAMES / ONLINE",
    "searchTerms": [
      "museum",
      "collection",
      "web",
      "games"
    ]
  },
  "launchBudgets": {
    "local": {
      "slowAfterMs": 5000,
      "heartbeatTimeoutMs": 8000,
      "timeoutMs": 15000
    },
    "remote": {
      "slowAfterMs": 10000,
      "heartbeatTimeoutMs": 15000,
      "timeoutMs": 30000
    }
  },
  "entries": [
    {
      "id": "vibebots",
      "version": "hosted-5b5d17ef-2026-07-19",
      "title": "VibeBots",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://vibebots.randroid.dev/mine",
      "network": "required",
      "compatibilityStatus": "partial",
      "surface": "museum",
      "displayIndex": "M1",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "robots"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Partial"
    },
    {
      "id": "mi-casa-es-su-casa",
      "version": "hosted-0c868be6-2026-07-19",
      "title": "Mi Casa Es Su Casa",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://mi-casa-es-su-casa.vercel.app",
      "network": "required",
      "compatibilityStatus": "unverified",
      "surface": "museum",
      "displayIndex": "M2",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "casa"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Unverified"
    },
    {
      "id": "determined",
      "version": "hosted-7d9a38dc-2026-07-19",
      "title": "Determined",
      "publisher": "Randroid's Dojo",
      "runtime": "remote-web",
      "entrypoint": "https://determined-khaki.vercel.app",
      "network": "required",
      "compatibilityStatus": "partial",
      "surface": "museum",
      "displayIndex": "M3",
      "searchDetail": "Museum catalog",
      "searchTerms": [
        "vibecoded",
        "online",
        "word",
        "game"
      ],
      "summary": "Hosted service · controller qualification pending",
      "statusLabel": "Partial"
    },
    {
      "id": "retro-2048",
      "version": "qualification-candidate-2026-07-23",
      "title": "2048",
      "publisher": "Gabriele Cirulli / Libretro",
      "runtime": "libretro",
      "entrypoint": "libretro:2048",
      "network": "offline",
      "compatibilityStatus": "unverified",
      "surface": "retro",
      "displayIndex": "Q1",
      "searchDetail": "Retro qualification candidate",
      "searchTerms": [
        "libretro",
        "smoke",
        "test",
        "public",
        "domain",
        "offline"
      ],
      "summary": "Contentless public-domain core · artifact qualification pending",
      "statusLabel": "Candidate"
    }
  ]
} as const satisfies LauncherCatalog;
